kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: no-auth-mysql-data-2
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
