apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotContent
metadata:
  name: new-snapshot-content-test
spec:
  snapshotClassName: csi-hostpath-snapclass
  source:
    name: no-auth-mysql-data 
    kind: PersistentVolumeClaim
  volumeSnapshotSource:
    csiVolumeSnapshotSource:
      creationTime:    1535478900692119403
      driver:          pxd.portworx.com 
      restoreSize:     1Gi
      snapshotHandle:  7bdd0de3-aaeb-11e8-9aae-0242ac110002
