kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
   name: koka-sc-local
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   openstorage.io/auth-secret-namespace: default
   openstorage.io/auth-secret-name: px-secret-admin1
   #openstorage.io/auth-secret-name: px-secret-expired
allowVolumeExpansion: true
