- name: remove all old docker
  yum: name={{ packages }} state=removed disable_gpg_check=yes
  vars:
    packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

- name: install docker ce yum repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker ce yum set obsolete
  command: yum-config-manager --setopt=obsoletes=0

- name: install docker ce
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - docker-ce-19.03.11
      - docker-ce-cli-19.03.11
      - containerd.io-1.2.13

- name: making docker dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/docker
    - /etc/systemd/system/docker.service.d

- name: copy docker settings
  copy: src=docker-daemon.json owner=root group=root dest=/etc/docker/daemon.json
