- name: install v1.13 kubernetes
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - kubelet-1.13.7-0
      - kubeadm-1.13.7-0
      - kubectl-1.13.7-0

- name: setting vars
  set_fact:
    kubeadm_kubernetes_version: v1.13.7 
    use_dockerce: true
