- name: install docker ce yum set obsolete
  command: yum-config-manager --save --setopt=obsoletes=0

- name: install docker ce yum repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- name: install v1.17 kubernetes
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - kubelet-1.17.15-0
      - kubeadm-1.17.15-0
      - kubectl-1.17.15-0

- name: setting vars
  set_fact:
    kubeadm_kubernetes_version: stable-1.17
    use_dockerce: true
