kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcsc001
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc-it
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

